# Generated by Django 5.2 on 2026-06-11 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('question_html', models.TextField()),
                ('choices', models.JSONField(blank=True, null=True)),
                ('answer', models.CharField(max_length=300)),
                ('explanation_html', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['question_set', 'number'],
            },
        ),
        migrations.CreateModel(
            name='AnswerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('chosen', models.CharField(blank=True, max_length=10, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to='quiz.question')),
            ],
            options={
                'ordering': ['-answered_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_type', models.CharField(choices=[('basic', '一問一答'), ('exam', '模擬試験')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('source_filename', models.CharField(max_length=300, unique=True)),
                ('order', models.IntegerField(default=999)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='notes.subject')),
            ],
            options={
                'ordering': ['order', 'source_filename'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.questionset'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_set', 'number')},
        ),
    ]
