# Generated by Django 5.2 on 2026-06-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_basic_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='questionset',
            name='series',
            field=models.IntegerField(default=0),
        ),
    ]
